name: First-Java-Actions
on: [push]
jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - name: files list
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name: after checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      - name: simple jvascript action
        id: greet

        uses: Hiba-moh/JavaScriptAction@v1
        with:
          who-to-greet: Hiba
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
